import { useState, useEffect } from 'react'
import { Mail, RefreshCw } from 'lucide-react'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/shared/components/ui/card'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/shared/components/ui/table'
import { Button } from '@/shared/components/ui/button'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogDescription } from '@/shared/components/ui/dialog'
import { Input } from '@/shared/components/ui/input'
import { Label } from '@/shared/components/ui/label'
import { fetchExportLogs, sendEmailToGermany, type ExportLog } from '../api/admin-api'
import { Badge } from '@/shared/components/ui/badge'

export function AdminExportHistory({ refreshTrigger }: { refreshTrigger: number }) {
    const [logs, setLogs] = useState<ExportLog[]>([])
    const [isLoading, setIsLoading] = useState(false)

    // Email Modal State
    const [isEmailModalOpen, setIsEmailModalOpen] = useState(false)
    const [selectedExport, setSelectedExport] = useState<ExportLog | null>(null)
    const [email, setEmail] = useState('')
    const [isSending, setIsSending] = useState(false)

    const loadLogs = async () => {
        setIsLoading(true)
        try {
            const data = await fetchExportLogs()
            setLogs(data)
        } catch (error) {
            console.error("Failed to load export history", error)
        } finally {
            setIsLoading(false)
        }
    }

    useEffect(() => {
        loadLogs()
    }, [refreshTrigger])

    const handleOpenEmailDialog = (log: ExportLog) => {
        setSelectedExport(log)
        setEmail('')
        setIsEmailModalOpen(true)
    }

    const handleSendEmail = async () => {
        if (!selectedExport) return
        setIsSending(true)
        try {
            const result = await sendEmailToGermany(selectedExport.ID, email || undefined)
            alert(`Email Sent:\n${result}`)
            setIsEmailModalOpen(false)
        } catch (error: any) {
            alert(`Email Failed:\n${error.message || 'Failed to send email. Check SMTP settings.'}`)
        } finally {
            setIsSending(false)
        }
    }

    const parseFiltersRender = (filterStr: string) => {
        try {
            const f = JSON.parse(filterStr)
            const badges = []
            if (f.year) badges.push(`Year: ${f.year}`)
            if (f.month) badges.push(`Month: ${f.month}`)
            if (f.from && f.to) badges.push(`Range: ${f.from} - ${f.to}`)
            if (f.userId) badges.push('User: Specific')
            if (f.projectId) badges.push('Project: Specific')
            return badges.length > 0 ? badges.join(' | ') : 'All'
        } catch {
            return 'Invalid Data'
        }
    }

    return (
        <Card>
            <CardHeader className="flex flex-row items-center justify-between">
                <div>
                    <CardTitle>Export History</CardTitle>
                    <CardDescription>Recent Excel exports generated by Admins</CardDescription>
                </div>
                <Button variant="ghost" size="icon" onClick={loadLogs} disabled={isLoading}>
                    <RefreshCw className={`h-4 w-4 ${isLoading ? 'animate-spin' : ''}`} />
                </Button>
            </CardHeader>
            <CardContent>
                <div className="rounded-md border">
                    <Table>
                        <TableHeader>
                            <TableRow>
                                <TableHead>Date</TableHead>
                                <TableHead>Period</TableHead>
                                <TableHead>Filters</TableHead>
                                <TableHead>Entries</TableHead>
                                <TableHead className="text-right">Action</TableHead>
                            </TableRow>
                        </TableHeader>
                        <TableBody>
                            {logs.length === 0 ? (
                                <TableRow>
                                    <TableCell colSpan={5} className="text-center text-muted-foreground h-24">
                                        No export history found.
                                    </TableCell>
                                </TableRow>
                            ) : (
                                logs.map((log) => (
                                    <TableRow key={log.ID}>
                                        <TableCell>{new Date(log.exportDate).toLocaleString()}</TableCell>
                                        <TableCell>
                                            <Badge variant="secondary">
                                                {log.fromDate} - {log.toDate}
                                            </Badge>
                                        </TableCell>
                                        <TableCell className="text-xs text-muted-foreground max-w-[200px] truncate">
                                            {parseFiltersRender(log.filters)}
                                        </TableCell>
                                        <TableCell>{log.totalEntries}</TableCell>
                                        <TableCell className="text-right">
                                            <Button
                                                variant="outline"
                                                size="sm"
                                                className="gap-2"
                                                onClick={() => handleOpenEmailDialog(log)}
                                            >
                                                <Mail className="h-4 w-4" />
                                                Email
                                            </Button>
                                        </TableCell>
                                    </TableRow>
                                ))
                            )}
                        </TableBody>
                    </Table>
                </div>
            </CardContent>

            {/* Email Dialog */}
            <Dialog open={isEmailModalOpen} onOpenChange={setIsEmailModalOpen}>
                <DialogContent>
                    <DialogHeader>
                        <DialogTitle>Send Export via Email</DialogTitle>
                        <DialogDescription>
                            This will send the export file ({selectedExport?.fromDate} to {selectedExport?.toDate}) to the German client.
                        </DialogDescription>
                    </DialogHeader>
                    <div className="space-y-4 py-4">
                        <div className="space-y-2">
                            <Label>Recipient Email (Optional)</Label>
                            <Input
                                placeholder="Contact email (leaves empty to use default env)"
                                value={email}
                                onChange={(e) => setEmail(e.target.value)}
                            />
                            <p className="text-xs text-muted-foreground">
                                If left blank, it uses the GERMANY_EMAIL configured in the backend environment.
                            </p>
                        </div>
                    </div>
                    <DialogFooter>
                        <Button variant="outline" onClick={() => setIsEmailModalOpen(false)}>Cancel</Button>
                        <Button onClick={handleSendEmail} disabled={isSending}>
                            {isSending ? 'Sending...' : 'Send Email'}
                        </Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>
        </Card>
    )
}
